[project]
name = 'Prediction-Market-AI'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.prediction-market-ai]
path = 'contracts/prediction-market-ai.clar'
clarity_version = 3
epoch = 3.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
